Resources:
  AutoScalingGroup:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    Properties:
      MinSize: "2"
      MaxSize: "10"
      DesiredCapacity: "4"
      LaunchConfigurationName: !Ref LaunchConfig
      VPCZoneIdentifier:
        - "subnet-12345678"
        - "subnet-87654321"
      Tags:
        - Key: "Name"
          Value: "WebServer"
          PropagateAtLaunch: "true"

  LaunchConfig:
    Type: "AWS::AutoScaling::LaunchConfiguration"
    Properties:
      InstanceType: "t3.medium"
      ImageId: "ami-0abcd12345efgh678"
      SecurityGroups:
        - !Ref SecurityGroup

  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Allow HTTP and HTTPS traffic"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "80"
          ToPort: "80"
          CidrIp: "0.0.0.0/0"
        - IpProtocol: "tcp"
          FromPort: "443"
          ToPort: "443"
          CidrIp: "0.0.0.0/0"
